name: Lint Check

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  eslint:
    name: Test Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test Lint
        run: npm run lint